services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    container_name: greenpro_api_dev
    command: npm run start:dev
    env_file:
      - .env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - api_node_modules:/app/node_modules
      - uploads_data:/app/uploads
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started

volumes:
  api_node_modules:
