import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class VerifyRecaptchaDto {
  @ApiProperty({
    description: 'reCAPTCHA token generated by frontend',
    example: '03AFcWeA....',
  })
  @IsString()
  @IsNotEmpty()
  captchaToken: string;
}

