export enum NotificationChannel {
  EMAIL = 'email',
  IN_APP = 'in_app',
  /** Future — register handler when implemented */
  SMS = 'sms',
  WHATSAPP = 'whatsapp',
  PUSH = 'push',
}

export enum NotificationTemplateCode {
  PRODUCT_APPROVED = 'PRODUCT_APPROVED',
  PRODUCT_REJECTED = 'PRODUCT_REJECTED',
  USER_CREATED = 'USER_CREATED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  OTP_VERIFICATION = 'OTP_VERIFICATION',
  VENDOR_REGISTRATION_COMPLETE = 'VENDOR_REGISTRATION_COMPLETE',
  URN_INITIAL_APPROVED = 'URN_INITIAL_APPROVED',
  URN_REGISTRATION_REJECTED = 'URN_REGISTRATION_REJECTED',
  URN_SUBMITTED_FOR_REVIEW = 'URN_SUBMITTED_FOR_REVIEW',
  CERTIFICATION_PAYMENT_SUBMITTED = 'CERTIFICATION_PAYMENT_SUBMITTED',
  CERTIFICATION_PAYMENT_APPROVED = 'CERTIFICATION_PAYMENT_APPROVED',
  MANUFACTURER_APPROVED = 'MANUFACTURER_APPROVED',
  MANUFACTURER_INACTIVE = 'MANUFACTURER_INACTIVE',
  MANUFACTURER_REJECTED = 'MANUFACTURER_REJECTED',
  PAYMENT_PROPOSAL_READY = 'PAYMENT_PROPOSAL_READY',
  PRODUCT_ENQUIRY_VENDOR = 'PRODUCT_ENQUIRY_VENDOR',
  CERTIFICATION_EXPIRY_REMINDER = 'CERTIFICATION_EXPIRY_REMINDER',
  URN_MERGED = 'URN_MERGED',
  PLANT_MERGED = 'PLANT_MERGED',
  RENEWAL_SUBMITTED = 'RENEWAL_SUBMITTED',
  RENEWAL_DECISION = 'RENEWAL_DECISION',
  RENEWAL_COMPLETED = 'RENEWAL_COMPLETED',
  PRODUCT_NAME_CHANGE_DECISION = 'PRODUCT_NAME_CHANGE_DECISION',
  GRIEVANCE_RESPONDED = 'GRIEVANCE_RESPONDED',
  GRIEVANCE_CLOSED = 'GRIEVANCE_CLOSED',
  ACCOUNT_DELETION_APPROVED = 'ACCOUNT_DELETION_APPROVED',
  ACCOUNT_DELETION_REJECTED = 'ACCOUNT_DELETION_REJECTED',
  ACCOUNT_DELETION_COMPLETED = 'ACCOUNT_DELETION_COMPLETED',
}

export type NotificationPayload = Record<string, unknown>;

export interface NotificationRecipient {
  userId?: string;
  email?: string;
}

export interface ChannelDeliveryResult {
  channel: NotificationChannel;
  success: boolean;
  skipped?: boolean;
  error?: string;
  /** Reserved for queue/retry metadata */
  attempts?: number;
  metadata?: Record<string, unknown>;
}

export interface NotificationSendResult {
  template: NotificationTemplateCode;
  recipientCount: number;
  results: ChannelDeliveryResult[];
}
