/**
 * Canonical audit action names. Prefer adding here instead of string literals.
 * HTTP mutations default to HTTP_MUTATION unless a route-specific mapping applies.
 */
export const AUDIT_ACTION = {
  HTTP_MUTATION: 'HTTP_MUTATION',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REFRESH: 'AUTH_REFRESH',
  AUTH_REGISTER_VENDOR: 'AUTH_REGISTER_VENDOR',
  AUTH_VERIFY_OTP: 'AUTH_VERIFY_OTP',
  AUTH_FORGOT_PASSWORD: 'AUTH_FORGOT_PASSWORD',
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_UPDATED: 'PAYMENT_UPDATED',
  PRODUCT_URN_STATUS_UPDATED: 'PRODUCT_URN_STATUS_UPDATED',
  ACTIVITY_LOG_CREATED: 'ACTIVITY_LOG_CREATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
