"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProductSchema = exports.Product = void 0;
var mongoose_1 = require("@nestjs/mongoose");
var mongoose_2 = require("mongoose");
var Product = function () {
    var _classDecorators = [(0, mongoose_1.Schema)({ collection: 'products' })];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _productId_decorators;
    var _productId_initializers = [];
    var _productId_extraInitializers = [];
    var _categoryId_decorators;
    var _categoryId_initializers = [];
    var _categoryId_extraInitializers = [];
    var _vendorId_decorators;
    var _vendorId_initializers = [];
    var _vendorId_extraInitializers = [];
    var _manufacturerId_decorators;
    var _manufacturerId_initializers = [];
    var _manufacturerId_extraInitializers = [];
    var _eoiNo_decorators;
    var _eoiNo_initializers = [];
    var _eoiNo_extraInitializers = [];
    var _eoiSequence_decorators;
    var _eoiSequence_initializers = [];
    var _eoiSequence_extraInitializers = [];
    var _previousEoiNo_decorators;
    var _previousEoiNo_initializers = [];
    var _previousEoiNo_extraInitializers = [];
    var _eoiReassignedAt_decorators;
    var _eoiReassignedAt_initializers = [];
    var _eoiReassignedAt_extraInitializers = [];
    var _rejectedAt_decorators;
    var _rejectedAt_initializers = [];
    var _rejectedAt_extraInitializers = [];
    var _urnNo_decorators;
    var _urnNo_initializers = [];
    var _urnNo_extraInitializers = [];
    var _mergedFromUrnNo_decorators;
    var _mergedFromUrnNo_initializers = [];
    var _mergedFromUrnNo_extraInitializers = [];
    var _productName_decorators;
    var _productName_initializers = [];
    var _productName_extraInitializers = [];
    var _productImage_decorators;
    var _productImage_initializers = [];
    var _productImage_extraInitializers = [];
    var _plantCount_decorators;
    var _plantCount_initializers = [];
    var _plantCount_extraInitializers = [];
    var _productDetails_decorators;
    var _productDetails_initializers = [];
    var _productDetails_extraInitializers = [];
    var _productPassport_decorators;
    var _productPassport_initializers = [];
    var _productPassport_extraInitializers = [];
    var _productType_decorators;
    var _productType_initializers = [];
    var _productType_extraInitializers = [];
    var _productStatus_decorators;
    var _productStatus_initializers = [];
    var _productStatus_extraInitializers = [];
    var _productRenewStatus_decorators;
    var _productRenewStatus_initializers = [];
    var _productRenewStatus_extraInitializers = [];
    var _renewCycleNo_decorators;
    var _renewCycleNo_initializers = [];
    var _renewCycleNo_extraInitializers = [];
    var _renewedDate_decorators;
    var _renewedDate_initializers = [];
    var _renewedDate_extraInitializers = [];
    var _urnStatus_decorators;
    var _urnStatus_initializers = [];
    var _urnStatus_extraInitializers = [];
    var _assessmentReportUrl_decorators;
    var _assessmentReportUrl_initializers = [];
    var _assessmentReportUrl_extraInitializers = [];
    var _rejectedDetails_decorators;
    var _rejectedDetails_initializers = [];
    var _rejectedDetails_extraInitializers = [];
    var _certifiedDate_decorators;
    var _certifiedDate_initializers = [];
    var _certifiedDate_extraInitializers = [];
    var _validtillDate_decorators;
    var _validtillDate_initializers = [];
    var _validtillDate_extraInitializers = [];
    var _firstNotifyDate_decorators;
    var _firstNotifyDate_initializers = [];
    var _firstNotifyDate_extraInitializers = [];
    var _secondNotifyDate_decorators;
    var _secondNotifyDate_initializers = [];
    var _secondNotifyDate_extraInitializers = [];
    var _thirdNotifyDate_decorators;
    var _thirdNotifyDate_initializers = [];
    var _thirdNotifyDate_extraInitializers = [];
    var _createdDate_decorators;
    var _createdDate_initializers = [];
    var _createdDate_extraInitializers = [];
    var _updatedDate_decorators;
    var _updatedDate_initializers = [];
    var _updatedDate_extraInitializers = [];
    var _is_deleted_decorators;
    var _is_deleted_initializers = [];
    var _is_deleted_extraInitializers = [];
    var _deleted_at_decorators;
    var _deleted_at_initializers = [];
    var _deleted_at_extraInitializers = [];
    var _deleted_by_decorators;
    var _deleted_by_initializers = [];
    var _deleted_by_extraInitializers = [];
    var _addedByAdminId_decorators;
    var _addedByAdminId_initializers = [];
    var _addedByAdminId_extraInitializers = [];
    var _discontinuedAt_decorators;
    var _discontinuedAt_initializers = [];
    var _discontinuedAt_extraInitializers = [];
    var _discontinuedBy_decorators;
    var _discontinuedBy_initializers = [];
    var _discontinuedBy_extraInitializers = [];
    var _discontinueReason_decorators;
    var _discontinueReason_initializers = [];
    var _discontinueReason_extraInitializers = [];
    var Product = _classThis = /** @class */ (function () {
        function Product_1() {
            this.productId = __runInitializers(this, _productId_initializers, void 0);
            this.categoryId = (__runInitializers(this, _productId_extraInitializers), __runInitializers(this, _categoryId_initializers, void 0));
            this.vendorId = (__runInitializers(this, _categoryId_extraInitializers), __runInitializers(this, _vendorId_initializers, void 0));
            this.manufacturerId = (__runInitializers(this, _vendorId_extraInitializers), __runInitializers(this, _manufacturerId_initializers, void 0));
            this.eoiNo = (__runInitializers(this, _manufacturerId_extraInitializers), __runInitializers(this, _eoiNo_initializers, void 0));
            /** Numeric suffix aligned with eoiNo (last 3 digits). */
            this.eoiSequence = (__runInitializers(this, _eoiNo_extraInitializers), __runInitializers(this, _eoiSequence_initializers, void 0));
            /** Previous eoiNo before reassignment on restore / undo-delete. */
            this.previousEoiNo = (__runInitializers(this, _eoiSequence_extraInitializers), __runInitializers(this, _previousEoiNo_initializers, void 0));
            this.eoiReassignedAt = (__runInitializers(this, _previousEoiNo_extraInitializers), __runInitializers(this, _eoiReassignedAt_initializers, void 0));
            this.rejectedAt = (__runInitializers(this, _eoiReassignedAt_extraInitializers), __runInitializers(this, _rejectedAt_initializers, void 0));
            this.urnNo = (__runInitializers(this, _rejectedAt_extraInitializers), __runInitializers(this, _urnNo_initializers, void 0));
            /** Set when this EOI was moved from another URN via admin merge. */
            this.mergedFromUrnNo = (__runInitializers(this, _urnNo_extraInitializers), __runInitializers(this, _mergedFromUrnNo_initializers, void 0));
            this.productName = (__runInitializers(this, _mergedFromUrnNo_extraInitializers), __runInitializers(this, _productName_initializers, void 0));
            this.productImage = (__runInitializers(this, _productName_extraInitializers), __runInitializers(this, _productImage_initializers, void 0));
            this.plantCount = (__runInitializers(this, _productImage_extraInitializers), __runInitializers(this, _plantCount_initializers, void 0));
            this.productDetails = (__runInitializers(this, _plantCount_extraInitializers), __runInitializers(this, _productDetails_initializers, void 0));
            this.productPassport = (__runInitializers(this, _productDetails_extraInitializers), __runInitializers(this, _productPassport_initializers, void 0));
            this.productType = (__runInitializers(this, _productPassport_extraInitializers), __runInitializers(this, _productType_initializers, void 0));
            this.productStatus = (__runInitializers(this, _productType_extraInitializers), __runInitializers(this, _productStatus_initializers, void 0));
            this.productRenewStatus = (__runInitializers(this, _productStatus_extraInitializers), __runInitializers(this, _productRenewStatus_initializers, void 0));
            /** 1-based renewal cycle number (matches `renewal_cycles.cycleNo` for this URN). */
            this.renewCycleNo = (__runInitializers(this, _productRenewStatus_extraInitializers), __runInitializers(this, _renewCycleNo_initializers, void 0));
            this.renewedDate = (__runInitializers(this, _renewCycleNo_extraInitializers), __runInitializers(this, _renewedDate_initializers, void 0));
            this.urnStatus = (__runInitializers(this, _renewedDate_extraInitializers), __runInitializers(this, _urnStatus_initializers, void 0));
            this.assessmentReportUrl = (__runInitializers(this, _urnStatus_extraInitializers), __runInitializers(this, _assessmentReportUrl_initializers, void 0));
            this.rejectedDetails = (__runInitializers(this, _assessmentReportUrl_extraInitializers), __runInitializers(this, _rejectedDetails_initializers, void 0));
            this.certifiedDate = (__runInitializers(this, _rejectedDetails_extraInitializers), __runInitializers(this, _certifiedDate_initializers, void 0));
            this.validtillDate = (__runInitializers(this, _certifiedDate_extraInitializers), __runInitializers(this, _validtillDate_initializers, void 0));
            this.firstNotifyDate = (__runInitializers(this, _validtillDate_extraInitializers), __runInitializers(this, _firstNotifyDate_initializers, void 0));
            this.secondNotifyDate = (__runInitializers(this, _firstNotifyDate_extraInitializers), __runInitializers(this, _secondNotifyDate_initializers, void 0));
            this.thirdNotifyDate = (__runInitializers(this, _secondNotifyDate_extraInitializers), __runInitializers(this, _thirdNotifyDate_initializers, void 0));
            this.createdDate = (__runInitializers(this, _thirdNotifyDate_extraInitializers), __runInitializers(this, _createdDate_initializers, void 0));
            this.updatedDate = (__runInitializers(this, _createdDate_extraInitializers), __runInitializers(this, _updatedDate_initializers, void 0));
            /** Soft delete — excluded from active listings and EOI sequence calculation */
            this.is_deleted = (__runInitializers(this, _updatedDate_extraInitializers), __runInitializers(this, _is_deleted_initializers, void 0));
            this.deleted_at = (__runInitializers(this, _is_deleted_extraInitializers), __runInitializers(this, _deleted_at_initializers, void 0));
            this.deleted_by = (__runInitializers(this, _deleted_at_extraInitializers), __runInitializers(this, _deleted_by_initializers, void 0));
            this.addedByAdminId = (__runInitializers(this, _deleted_by_extraInitializers), __runInitializers(this, _addedByAdminId_initializers, void 0));
            this.discontinuedAt = (__runInitializers(this, _addedByAdminId_extraInitializers), __runInitializers(this, _discontinuedAt_initializers, void 0));
            this.discontinuedBy = (__runInitializers(this, _discontinuedAt_extraInitializers), __runInitializers(this, _discontinuedBy_initializers, void 0));
            this.discontinueReason = (__runInitializers(this, _discontinuedBy_extraInitializers), __runInitializers(this, _discontinueReason_initializers, void 0));
            __runInitializers(this, _discontinueReason_extraInitializers);
        }
        return Product_1;
    }());
    __setFunctionName(_classThis, "Product");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _productId_decorators = [(0, mongoose_1.Prop)({ required: true, unique: true })];
        _categoryId_decorators = [(0, mongoose_1.Prop)({ type: mongoose_2.Types.ObjectId, ref: 'Category', required: true })];
        _vendorId_decorators = [(0, mongoose_1.Prop)({ type: mongoose_2.Types.ObjectId, ref: 'Vendor', required: true })];
        _manufacturerId_decorators = [(0, mongoose_1.Prop)({ type: mongoose_2.Types.ObjectId, ref: 'Manufacturer', required: true })];
        _eoiNo_decorators = [(0, mongoose_1.Prop)({ required: true })];
        _eoiSequence_decorators = [(0, mongoose_1.Prop)()];
        _previousEoiNo_decorators = [(0, mongoose_1.Prop)()];
        _eoiReassignedAt_decorators = [(0, mongoose_1.Prop)({ type: Date })];
        _rejectedAt_decorators = [(0, mongoose_1.Prop)({ type: Date })];
        _urnNo_decorators = [(0, mongoose_1.Prop)({ required: true })];
        _mergedFromUrnNo_decorators = [(0, mongoose_1.Prop)()];
        _productName_decorators = [(0, mongoose_1.Prop)({ required: true })];
        _productImage_decorators = [(0, mongoose_1.Prop)()];
        _plantCount_decorators = [(0, mongoose_1.Prop)({ required: true, default: 0 })];
        _productDetails_decorators = [(0, mongoose_1.Prop)()];
        _productPassport_decorators = [(0, mongoose_1.Prop)()];
        _productType_decorators = [(0, mongoose_1.Prop)({ default: 0 })];
        _productStatus_decorators = [(0, mongoose_1.Prop)({ default: 0 })];
        _productRenewStatus_decorators = [(0, mongoose_1.Prop)({ default: 0 })];
        _renewCycleNo_decorators = [(0, mongoose_1.Prop)()];
        _renewedDate_decorators = [(0, mongoose_1.Prop)()];
        _urnStatus_decorators = [(0, mongoose_1.Prop)({ default: 0 })];
        _assessmentReportUrl_decorators = [(0, mongoose_1.Prop)()];
        _rejectedDetails_decorators = [(0, mongoose_1.Prop)()];
        _certifiedDate_decorators = [(0, mongoose_1.Prop)()];
        _validtillDate_decorators = [(0, mongoose_1.Prop)()];
        _firstNotifyDate_decorators = [(0, mongoose_1.Prop)()];
        _secondNotifyDate_decorators = [(0, mongoose_1.Prop)()];
        _thirdNotifyDate_decorators = [(0, mongoose_1.Prop)()];
        _createdDate_decorators = [(0, mongoose_1.Prop)({ required: true })];
        _updatedDate_decorators = [(0, mongoose_1.Prop)({ required: true })];
        _is_deleted_decorators = [(0, mongoose_1.Prop)({ default: false })];
        _deleted_at_decorators = [(0, mongoose_1.Prop)({ type: Date, default: null })];
        _deleted_by_decorators = [(0, mongoose_1.Prop)({ type: mongoose_2.Types.ObjectId, ref: 'User', default: null })];
        _addedByAdminId_decorators = [(0, mongoose_1.Prop)({ type: mongoose_2.Types.ObjectId, ref: 'User' })];
        _discontinuedAt_decorators = [(0, mongoose_1.Prop)({ type: Date, default: null })];
        _discontinuedBy_decorators = [(0, mongoose_1.Prop)({ type: mongoose_2.Types.ObjectId, ref: 'User', default: null })];
        _discontinueReason_decorators = [(0, mongoose_1.Prop)()];
        __esDecorate(null, null, _productId_decorators, { kind: "field", name: "productId", static: false, private: false, access: { has: function (obj) { return "productId" in obj; }, get: function (obj) { return obj.productId; }, set: function (obj, value) { obj.productId = value; } }, metadata: _metadata }, _productId_initializers, _productId_extraInitializers);
        __esDecorate(null, null, _categoryId_decorators, { kind: "field", name: "categoryId", static: false, private: false, access: { has: function (obj) { return "categoryId" in obj; }, get: function (obj) { return obj.categoryId; }, set: function (obj, value) { obj.categoryId = value; } }, metadata: _metadata }, _categoryId_initializers, _categoryId_extraInitializers);
        __esDecorate(null, null, _vendorId_decorators, { kind: "field", name: "vendorId", static: false, private: false, access: { has: function (obj) { return "vendorId" in obj; }, get: function (obj) { return obj.vendorId; }, set: function (obj, value) { obj.vendorId = value; } }, metadata: _metadata }, _vendorId_initializers, _vendorId_extraInitializers);
        __esDecorate(null, null, _manufacturerId_decorators, { kind: "field", name: "manufacturerId", static: false, private: false, access: { has: function (obj) { return "manufacturerId" in obj; }, get: function (obj) { return obj.manufacturerId; }, set: function (obj, value) { obj.manufacturerId = value; } }, metadata: _metadata }, _manufacturerId_initializers, _manufacturerId_extraInitializers);
        __esDecorate(null, null, _eoiNo_decorators, { kind: "field", name: "eoiNo", static: false, private: false, access: { has: function (obj) { return "eoiNo" in obj; }, get: function (obj) { return obj.eoiNo; }, set: function (obj, value) { obj.eoiNo = value; } }, metadata: _metadata }, _eoiNo_initializers, _eoiNo_extraInitializers);
        __esDecorate(null, null, _eoiSequence_decorators, { kind: "field", name: "eoiSequence", static: false, private: false, access: { has: function (obj) { return "eoiSequence" in obj; }, get: function (obj) { return obj.eoiSequence; }, set: function (obj, value) { obj.eoiSequence = value; } }, metadata: _metadata }, _eoiSequence_initializers, _eoiSequence_extraInitializers);
        __esDecorate(null, null, _previousEoiNo_decorators, { kind: "field", name: "previousEoiNo", static: false, private: false, access: { has: function (obj) { return "previousEoiNo" in obj; }, get: function (obj) { return obj.previousEoiNo; }, set: function (obj, value) { obj.previousEoiNo = value; } }, metadata: _metadata }, _previousEoiNo_initializers, _previousEoiNo_extraInitializers);
        __esDecorate(null, null, _eoiReassignedAt_decorators, { kind: "field", name: "eoiReassignedAt", static: false, private: false, access: { has: function (obj) { return "eoiReassignedAt" in obj; }, get: function (obj) { return obj.eoiReassignedAt; }, set: function (obj, value) { obj.eoiReassignedAt = value; } }, metadata: _metadata }, _eoiReassignedAt_initializers, _eoiReassignedAt_extraInitializers);
        __esDecorate(null, null, _rejectedAt_decorators, { kind: "field", name: "rejectedAt", static: false, private: false, access: { has: function (obj) { return "rejectedAt" in obj; }, get: function (obj) { return obj.rejectedAt; }, set: function (obj, value) { obj.rejectedAt = value; } }, metadata: _metadata }, _rejectedAt_initializers, _rejectedAt_extraInitializers);
        __esDecorate(null, null, _urnNo_decorators, { kind: "field", name: "urnNo", static: false, private: false, access: { has: function (obj) { return "urnNo" in obj; }, get: function (obj) { return obj.urnNo; }, set: function (obj, value) { obj.urnNo = value; } }, metadata: _metadata }, _urnNo_initializers, _urnNo_extraInitializers);
        __esDecorate(null, null, _mergedFromUrnNo_decorators, { kind: "field", name: "mergedFromUrnNo", static: false, private: false, access: { has: function (obj) { return "mergedFromUrnNo" in obj; }, get: function (obj) { return obj.mergedFromUrnNo; }, set: function (obj, value) { obj.mergedFromUrnNo = value; } }, metadata: _metadata }, _mergedFromUrnNo_initializers, _mergedFromUrnNo_extraInitializers);
        __esDecorate(null, null, _productName_decorators, { kind: "field", name: "productName", static: false, private: false, access: { has: function (obj) { return "productName" in obj; }, get: function (obj) { return obj.productName; }, set: function (obj, value) { obj.productName = value; } }, metadata: _metadata }, _productName_initializers, _productName_extraInitializers);
        __esDecorate(null, null, _productImage_decorators, { kind: "field", name: "productImage", static: false, private: false, access: { has: function (obj) { return "productImage" in obj; }, get: function (obj) { return obj.productImage; }, set: function (obj, value) { obj.productImage = value; } }, metadata: _metadata }, _productImage_initializers, _productImage_extraInitializers);
        __esDecorate(null, null, _plantCount_decorators, { kind: "field", name: "plantCount", static: false, private: false, access: { has: function (obj) { return "plantCount" in obj; }, get: function (obj) { return obj.plantCount; }, set: function (obj, value) { obj.plantCount = value; } }, metadata: _metadata }, _plantCount_initializers, _plantCount_extraInitializers);
        __esDecorate(null, null, _productDetails_decorators, { kind: "field", name: "productDetails", static: false, private: false, access: { has: function (obj) { return "productDetails" in obj; }, get: function (obj) { return obj.productDetails; }, set: function (obj, value) { obj.productDetails = value; } }, metadata: _metadata }, _productDetails_initializers, _productDetails_extraInitializers);
        __esDecorate(null, null, _productPassport_decorators, { kind: "field", name: "productPassport", static: false, private: false, access: { has: function (obj) { return "productPassport" in obj; }, get: function (obj) { return obj.productPassport; }, set: function (obj, value) { obj.productPassport = value; } }, metadata: _metadata }, _productPassport_initializers, _productPassport_extraInitializers);
        __esDecorate(null, null, _productType_decorators, { kind: "field", name: "productType", static: false, private: false, access: { has: function (obj) { return "productType" in obj; }, get: function (obj) { return obj.productType; }, set: function (obj, value) { obj.productType = value; } }, metadata: _metadata }, _productType_initializers, _productType_extraInitializers);
        __esDecorate(null, null, _productStatus_decorators, { kind: "field", name: "productStatus", static: false, private: false, access: { has: function (obj) { return "productStatus" in obj; }, get: function (obj) { return obj.productStatus; }, set: function (obj, value) { obj.productStatus = value; } }, metadata: _metadata }, _productStatus_initializers, _productStatus_extraInitializers);
        __esDecorate(null, null, _productRenewStatus_decorators, { kind: "field", name: "productRenewStatus", static: false, private: false, access: { has: function (obj) { return "productRenewStatus" in obj; }, get: function (obj) { return obj.productRenewStatus; }, set: function (obj, value) { obj.productRenewStatus = value; } }, metadata: _metadata }, _productRenewStatus_initializers, _productRenewStatus_extraInitializers);
        __esDecorate(null, null, _renewCycleNo_decorators, { kind: "field", name: "renewCycleNo", static: false, private: false, access: { has: function (obj) { return "renewCycleNo" in obj; }, get: function (obj) { return obj.renewCycleNo; }, set: function (obj, value) { obj.renewCycleNo = value; } }, metadata: _metadata }, _renewCycleNo_initializers, _renewCycleNo_extraInitializers);
        __esDecorate(null, null, _renewedDate_decorators, { kind: "field", name: "renewedDate", static: false, private: false, access: { has: function (obj) { return "renewedDate" in obj; }, get: function (obj) { return obj.renewedDate; }, set: function (obj, value) { obj.renewedDate = value; } }, metadata: _metadata }, _renewedDate_initializers, _renewedDate_extraInitializers);
        __esDecorate(null, null, _urnStatus_decorators, { kind: "field", name: "urnStatus", static: false, private: false, access: { has: function (obj) { return "urnStatus" in obj; }, get: function (obj) { return obj.urnStatus; }, set: function (obj, value) { obj.urnStatus = value; } }, metadata: _metadata }, _urnStatus_initializers, _urnStatus_extraInitializers);
        __esDecorate(null, null, _assessmentReportUrl_decorators, { kind: "field", name: "assessmentReportUrl", static: false, private: false, access: { has: function (obj) { return "assessmentReportUrl" in obj; }, get: function (obj) { return obj.assessmentReportUrl; }, set: function (obj, value) { obj.assessmentReportUrl = value; } }, metadata: _metadata }, _assessmentReportUrl_initializers, _assessmentReportUrl_extraInitializers);
        __esDecorate(null, null, _rejectedDetails_decorators, { kind: "field", name: "rejectedDetails", static: false, private: false, access: { has: function (obj) { return "rejectedDetails" in obj; }, get: function (obj) { return obj.rejectedDetails; }, set: function (obj, value) { obj.rejectedDetails = value; } }, metadata: _metadata }, _rejectedDetails_initializers, _rejectedDetails_extraInitializers);
        __esDecorate(null, null, _certifiedDate_decorators, { kind: "field", name: "certifiedDate", static: false, private: false, access: { has: function (obj) { return "certifiedDate" in obj; }, get: function (obj) { return obj.certifiedDate; }, set: function (obj, value) { obj.certifiedDate = value; } }, metadata: _metadata }, _certifiedDate_initializers, _certifiedDate_extraInitializers);
        __esDecorate(null, null, _validtillDate_decorators, { kind: "field", name: "validtillDate", static: false, private: false, access: { has: function (obj) { return "validtillDate" in obj; }, get: function (obj) { return obj.validtillDate; }, set: function (obj, value) { obj.validtillDate = value; } }, metadata: _metadata }, _validtillDate_initializers, _validtillDate_extraInitializers);
        __esDecorate(null, null, _firstNotifyDate_decorators, { kind: "field", name: "firstNotifyDate", static: false, private: false, access: { has: function (obj) { return "firstNotifyDate" in obj; }, get: function (obj) { return obj.firstNotifyDate; }, set: function (obj, value) { obj.firstNotifyDate = value; } }, metadata: _metadata }, _firstNotifyDate_initializers, _firstNotifyDate_extraInitializers);
        __esDecorate(null, null, _secondNotifyDate_decorators, { kind: "field", name: "secondNotifyDate", static: false, private: false, access: { has: function (obj) { return "secondNotifyDate" in obj; }, get: function (obj) { return obj.secondNotifyDate; }, set: function (obj, value) { obj.secondNotifyDate = value; } }, metadata: _metadata }, _secondNotifyDate_initializers, _secondNotifyDate_extraInitializers);
        __esDecorate(null, null, _thirdNotifyDate_decorators, { kind: "field", name: "thirdNotifyDate", static: false, private: false, access: { has: function (obj) { return "thirdNotifyDate" in obj; }, get: function (obj) { return obj.thirdNotifyDate; }, set: function (obj, value) { obj.thirdNotifyDate = value; } }, metadata: _metadata }, _thirdNotifyDate_initializers, _thirdNotifyDate_extraInitializers);
        __esDecorate(null, null, _createdDate_decorators, { kind: "field", name: "createdDate", static: false, private: false, access: { has: function (obj) { return "createdDate" in obj; }, get: function (obj) { return obj.createdDate; }, set: function (obj, value) { obj.createdDate = value; } }, metadata: _metadata }, _createdDate_initializers, _createdDate_extraInitializers);
        __esDecorate(null, null, _updatedDate_decorators, { kind: "field", name: "updatedDate", static: false, private: false, access: { has: function (obj) { return "updatedDate" in obj; }, get: function (obj) { return obj.updatedDate; }, set: function (obj, value) { obj.updatedDate = value; } }, metadata: _metadata }, _updatedDate_initializers, _updatedDate_extraInitializers);
        __esDecorate(null, null, _is_deleted_decorators, { kind: "field", name: "is_deleted", static: false, private: false, access: { has: function (obj) { return "is_deleted" in obj; }, get: function (obj) { return obj.is_deleted; }, set: function (obj, value) { obj.is_deleted = value; } }, metadata: _metadata }, _is_deleted_initializers, _is_deleted_extraInitializers);
        __esDecorate(null, null, _deleted_at_decorators, { kind: "field", name: "deleted_at", static: false, private: false, access: { has: function (obj) { return "deleted_at" in obj; }, get: function (obj) { return obj.deleted_at; }, set: function (obj, value) { obj.deleted_at = value; } }, metadata: _metadata }, _deleted_at_initializers, _deleted_at_extraInitializers);
        __esDecorate(null, null, _deleted_by_decorators, { kind: "field", name: "deleted_by", static: false, private: false, access: { has: function (obj) { return "deleted_by" in obj; }, get: function (obj) { return obj.deleted_by; }, set: function (obj, value) { obj.deleted_by = value; } }, metadata: _metadata }, _deleted_by_initializers, _deleted_by_extraInitializers);
        __esDecorate(null, null, _addedByAdminId_decorators, { kind: "field", name: "addedByAdminId", static: false, private: false, access: { has: function (obj) { return "addedByAdminId" in obj; }, get: function (obj) { return obj.addedByAdminId; }, set: function (obj, value) { obj.addedByAdminId = value; } }, metadata: _metadata }, _addedByAdminId_initializers, _addedByAdminId_extraInitializers);
        __esDecorate(null, null, _discontinuedAt_decorators, { kind: "field", name: "discontinuedAt", static: false, private: false, access: { has: function (obj) { return "discontinuedAt" in obj; }, get: function (obj) { return obj.discontinuedAt; }, set: function (obj, value) { obj.discontinuedAt = value; } }, metadata: _metadata }, _discontinuedAt_initializers, _discontinuedAt_extraInitializers);
        __esDecorate(null, null, _discontinuedBy_decorators, { kind: "field", name: "discontinuedBy", static: false, private: false, access: { has: function (obj) { return "discontinuedBy" in obj; }, get: function (obj) { return obj.discontinuedBy; }, set: function (obj, value) { obj.discontinuedBy = value; } }, metadata: _metadata }, _discontinuedBy_initializers, _discontinuedBy_extraInitializers);
        __esDecorate(null, null, _discontinueReason_decorators, { kind: "field", name: "discontinueReason", static: false, private: false, access: { has: function (obj) { return "discontinueReason" in obj; }, get: function (obj) { return obj.discontinueReason; }, set: function (obj, value) { obj.discontinueReason = value; } }, metadata: _metadata }, _discontinueReason_initializers, _discontinueReason_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Product = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Product = _classThis;
}();
exports.Product = Product;
exports.ProductSchema = mongoose_1.SchemaFactory.createForClass(Product);
// Unified lifecycle listing indexes
exports.ProductSchema.index({ productStatus: 1 });
exports.ProductSchema.index({ productType: 1 });
exports.ProductSchema.index({ manufacturerId: 1 });
exports.ProductSchema.index({ categoryId: 1 });
exports.ProductSchema.index({ createdDate: -1 });
exports.ProductSchema.index({ validtillDate: 1 });
exports.ProductSchema.index({ urnNo: 1, is_deleted: 1, productStatus: 1 });
exports.ProductSchema.index({ urnNo: 1, eoiNo: 1 });
exports.ProductSchema.index({ manufacturerId: 1, is_deleted: 1, createdDate: 1 });
exports.ProductSchema.index({ manufacturerId: 1, is_deleted: 1, eoiNo: 1 });
exports.ProductSchema.index({ manufacturerId: 1, productStatus: 1, is_deleted: 1 });
exports.ProductSchema.index({ vendorId: 1, is_deleted: 1, productStatus: 1, createdDate: -1 });
exports.ProductSchema.index({ vendorId: 1, is_deleted: 1, urnNo: 1 });
/** Admin dashboard aggregations / activity center */
exports.ProductSchema.index({ is_deleted: 1, productStatus: 1, createdDate: -1 });
exports.ProductSchema.index({ is_deleted: 1, productStatus: 1, urnStatus: 1 });
exports.ProductSchema.index({ is_deleted: 1, productStatus: 1, validtillDate: 1 });
exports.ProductSchema.index({
    is_deleted: 1,
    categoryId: 1,
    manufacturerId: 1,
    productStatus: 1,
});
